//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATCHRM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string xxx {
            get {
                return ((string)(this["xxx"]));
            }
            set {
                this["xxx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AboveLeft")]
        public global::System.Windows.Forms.ToolStripDropDownDirection Newdirection {
            get {
                return ((global::System.Windows.Forms.ToolStripDropDownDirection)(this["Newdirection"]));
            }
            set {
                this["Newdirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BelowRight")]
        public global::System.Windows.Forms.ToolStripDropDownDirection foractrion {
            get {
                return ((global::System.Windows.Forms.ToolStripDropDownDirection)(this["foractrion"]));
            }
            set {
                this["foractrion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AboveRight")]
        public global::System.Windows.Forms.ToolStripDropDownDirection foractionnew {
            get {
                return ((global::System.Windows.Forms.ToolStripDropDownDirection)(this["foractionnew"]));
            }
            set {
                this["foractionnew"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IT-DEPT\\MSSQLSERVERRAJ;Initial Catalog=ATCHRM;Persist Security Info=T" +
            "rue;User ID=sa")]
        public string ATCHRMConnectionString {
            get {
                return ((string)(this["ATCHRMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IT-DEPT\\MSSQLSERVERRAJ;Initial Catalog=ATCHRM;Persist Security Info=T" +
            "rue;User ID=sa;Password=sreenath")]
        public string ATCHRMConnectionString1 {
            get {
                return ((string)(this["ATCHRMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=197.232.31.250;Initial Catalog=ATCHRM;Persist Security Info=True;User" +
            " ID=sa;Password=admin_123")]
        public string ATCHRMConnectionString2 {
            get {
                return ((string)(this["ATCHRMConnectionString2"]));
            }
        }
    }
}
